#!/bin/bash
echo 'net-tools Installation Script'
sudo apt update
sudo apt install -y net-tools
which ifconfig
ifconfig

echo 'Telnet Installation script'
sudo apt update
sudo apt install -y telnet

echo 'Puppet Installation script'
sudo apt update
sudo apt install puppet
puppet --version
which puppet

echo 'Ansible Installation script'
sudo apt update
sudo apt install ansible
ansible --version
which ansible
#merging to master
